name: SonarCloud Analysis
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build and analyze
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0' 
        
    - name: Install SonarScanner for .NET
      run: |
        dotnet tool install --global dotnet-sonarscanner
        
    - name: Begin SonarCloud analysis
      run: |
        dotnet-sonarscanner begin /k:"xington231_checkpoints_devops" /o:"xington231" /d:sonar.token="${{ secrets.SONAR_TOKEN }}" /d:sonar.host.url="https://sonarcloud.io" /d:sonar.branch.name=${{ github.ref_name }}
        
    - name: Restore dependencies
      working-directory: calculator
      run: dotnet restore
        
    - name: Build project with dotnet
      working-directory: calculator 
      run: dotnet build ConsoleApp60.sln --configuration Release --verbosity normal
        
    - name: End SonarCloud analysis
      run: |
        dotnet-sonarscanner end /d:sonar.token="${{ secrets.SONAR_TOKEN }}"

